// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

// Protobuf Java Version: 3.25.0
package net.mahtabalam.protos;

public interface GetAllProductsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllProductsRequest)
    com.google.protobuf.MessageOrBuilder {
}
