// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

// Protobuf Java Version: 3.25.0
package net.mahtabalam.protos;

public interface GetAllProductsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetAllProductsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Product products = 1;</code>
   */
  java.util.List<net.mahtabalam.protos.Product> 
      getProductsList();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  net.mahtabalam.protos.Product getProducts(int index);
  /**
   * <code>repeated .Product products = 1;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  java.util.List<? extends net.mahtabalam.protos.ProductOrBuilder> 
      getProductsOrBuilderList();
  /**
   * <code>repeated .Product products = 1;</code>
   */
  net.mahtabalam.protos.ProductOrBuilder getProductsOrBuilder(
      int index);
}
