// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

// Protobuf Java Version: 3.25.0
package net.mahtabalam.protos;

public interface GetProductByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetProductByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Product product = 1;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <code>.Product product = 1;</code>
   * @return The product.
   */
  net.mahtabalam.protos.Product getProduct();
  /**
   * <code>.Product product = 1;</code>
   */
  net.mahtabalam.protos.ProductOrBuilder getProductOrBuilder();
}
