// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProductService.proto

// Protobuf Java Version: 3.25.0
package net.mahtabalam.protos;

public final class ProductServiceProto {
  private ProductServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Product_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllProductsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllProductsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetAllProductsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetAllProductsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProductByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProductByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetProductByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetProductByIdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteProductRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteProductRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ProductService.proto\"\247\001\n\007Product\022\021\n\tpr" +
      "oductId\030\001 \001(\t\022\023\n\013productName\030\002 \001(\t\022\023\n\013de" +
      "scription\030\003 \001(\t\022,\n\nattributes\030\004 \003(\0132\030.Pr" +
      "oduct.AttributesEntry\0321\n\017AttributesEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\".\n\021AddP" +
      "roductRequest\022\031\n\007product\030\001 \001(\0132\010.Product" +
      "\"%\n\022AddProductResponse\022\017\n\007message\030\001 \001(\t\"" +
      "\027\n\025GetAllProductsRequest\"4\n\026GetAllProduc" +
      "tsResponse\022\032\n\010products\030\001 \003(\0132\010.Product\"*" +
      "\n\025GetProductByIdRequest\022\021\n\tproductId\030\001 \001" +
      "(\t\"3\n\026GetProductByIdResponse\022\031\n\007product\030" +
      "\001 \001(\0132\010.Product\"1\n\024UpdateProductRequest\022" +
      "\031\n\007product\030\001 \001(\0132\010.Product\"(\n\025UpdateProd" +
      "uctResponse\022\017\n\007message\030\001 \001(\t\")\n\024DeletePr" +
      "oductRequest\022\021\n\tproductId\030\001 \001(\t\"(\n\025Delet" +
      "eProductResponse\022\017\n\007message\030\001 \001(\t2\315\002\n\016Pr" +
      "oductService\0225\n\nAddProduct\022\022.AddProductR" +
      "equest\032\023.AddProductResponse\022A\n\016GetAllPro" +
      "ducts\022\026.GetAllProductsRequest\032\027.GetAllPr" +
      "oductsResponse\022A\n\016GetProductById\022\026.GetPr" +
      "oductByIdRequest\032\027.GetProductByIdRespons" +
      "e\022>\n\rUpdateProduct\022\025.UpdateProductReques" +
      "t\032\026.UpdateProductResponse\022>\n\rDeleteProdu" +
      "ct\022\025.DeleteProductRequest\032\026.DeleteProduc" +
      "tResponseB.\n\025net.mahtabalam.protosB\023Prod" +
      "uctServiceProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "ProductId", "ProductName", "Description", "Attributes", });
    internal_static_Product_AttributesEntry_descriptor =
      internal_static_Product_descriptor.getNestedTypes().get(0);
    internal_static_Product_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Product_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_AddProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddProductRequest_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_AddProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_AddProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddProductResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_GetAllProductsRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_GetAllProductsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllProductsRequest_descriptor,
        new java.lang.String[] { });
    internal_static_GetAllProductsResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_GetAllProductsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetAllProductsResponse_descriptor,
        new java.lang.String[] { "Products", });
    internal_static_GetProductByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GetProductByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProductByIdRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_GetProductByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetProductByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetProductByIdResponse_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_UpdateProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_UpdateProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateProductRequest_descriptor,
        new java.lang.String[] { "Product", });
    internal_static_UpdateProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_UpdateProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateProductResponse_descriptor,
        new java.lang.String[] { "Message", });
    internal_static_DeleteProductRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_DeleteProductRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteProductRequest_descriptor,
        new java.lang.String[] { "ProductId", });
    internal_static_DeleteProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DeleteProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteProductResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
